#!/usr/bin/env python3
"""Build README and HTML from profile.json. Run with --check to validate edits."""

import argparse
import hashlib
import re
import shutil
from html import escape
from pathlib import Path

from profile_assets import build_assets
from profile_config import load_profile

ROOT = Path(__file__).resolve().parents[1]


def logo_picture(item):
    if item['logo'] is None:
        return ''
    name = item['id']
    return f'<img src="assets/logos/themed/{name}-light.svg" height="{item["logo"]["height"]:g}" align="middle" alt="">'


def contact_links(profile):
    links = [f'<a href="{escape(item["url"], quote=True)}">{escape(item["label"])} ↗</a>' for item in profile['links']]
    return ' &nbsp; / &nbsp; '.join(links)


def project_name(project):
    lines = project.get('name_lines')
    if not lines:
        return escape(project['name']).replace(' ', '&nbsp;')
    return '<br>'.join(escape(line) for line in lines)


def affiliation_markup(item):
    icon = logo_picture(item)
    link = f'<a href="{escape(item["url"], quote=True)}">{escape(item["label"])}</a>'
    logo = f'<span class="school-logo" style="--logo-height:{item["logo"]["height"] / 16:g}em">{icon}</span>' if icon else ''
    return f'<span class="affiliation">{logo}<span class="affiliation-text">{link}</span></span>'


def readme_logo(item, align='middle'):
    """Keep the logo link identical to its accompanying text link."""
    if item['logo'] is None:
        return ''
    asset = f'assets/logos/themed/{item["id"]}-light.svg'
    return f'<a href="{escape(item["url"], quote=True)}"><img src="{asset}" height="{item["logo"]["height"]:g}" align="{align}" alt="{escape(item.get("name", item.get("label", "")), quote=True)} logo"></a>'


def readme(profile):
    parts = ['<!-- Generated by scripts/build_profile.py. Edit profile.json; see EDITING.md. -->']
    parts.append(f'<h1><samp>Hi, I\'m {escape(profile["name"])}.</samp></h1>\n')
    affiliations = []
    for item in profile['affiliations']:
        # GitHub preserves absmiddle, which maps to vertical-align: middle.
        # The legacy "middle" value centers on the baseline, not the text.
        icon = readme_logo(item, align='absmiddle')
        link = f'<a href="{escape(item["url"], quote=True)}">{escape(item["label"])}</a>'
        affiliations.append((f'{icon}&nbsp;' if icon else '') + link)
    if affiliations:
        parts.append(f'<p><b><samp>{" &nbsp; / &nbsp; ".join(affiliations)}</samp></b></p>\n')
    parts.append(f'<p>{highlighted_intro(profile)}</p>\n')
    groups = [group for group in profile['groups'] if group['projects']]
    heading_width = max((len(group['name']) for group in groups), default=0)
    for group in groups:
        links = []
        for project in group['projects']:
            icon = readme_logo(project)
            link = f'<a href="{escape(project["url"], quote=True)}">{escape(project["name"]).replace(" ", "&nbsp;")}</a>'
            links.append(link + ('&nbsp;' + icon if icon else ''))
        # Padding inside the same monospace/small element gives all category
        # labels the same width without GitHub's table borders or striped rows.
        padding = '&nbsp;' * (heading_width - len(group['name']))
        parts.append(f'<p><samp><b><small>· {escape(group["name"])}{padding}</small>&nbsp;&nbsp; {" · ".join(links)}</b></samp></p>\n')
    if profile['links']:
        parts.append(f'<p><b><samp>{contact_links(profile)}</samp></b></p>\n')
    return '\n'.join(parts)


def highlighted_intro(profile):
    highlights = profile['intro_highlights']
    if not highlights:
        return escape(profile['intro'])
    pattern = '(' + '|'.join(re.escape(value) for value in sorted(highlights, key=len, reverse=True)) + ')'
    pieces = re.split(pattern, profile['intro'])
    return ''.join(f'<strong>{escape(piece)}</strong>' if piece in highlights else escape(piece) for piece in pieces)


def animated_intro(profile):
    highlights = profile['intro_highlights']
    if not highlights:
        return escape(profile['intro'])
    pattern = '(' + '|'.join(re.escape(value) for value in sorted(highlights, key=len, reverse=True)) + ')'
    pieces = re.split(pattern, profile['intro'])
    def keyword(word):
        letters = ''.join(f'<span class="keyword-letter" style="--letter-index:{i}">{escape(letter).replace(" ", "&#160;")}</span>' for i, letter in enumerate(word))
        # Keep a single text copy for selection and assistive technology.
        return f'<em><span class="keyword-letters">{letters}</span></em>'
    return ''.join(keyword(piece) if piece in highlights else escape(piece) for piece in pieces)


def page(profile):
    groups = []
    for i, group in enumerate(profile['groups'], 1):
        if not group['projects']:
            continue
        projects = []
        for project_index, project in enumerate(group['projects']):
            icon = logo_picture(project)
            logo = f'<span class="project-logo">{icon}</span>' if icon else ''
            title = f' title="{escape(project["description"], quote=True)}"' if project.get('description') else ''
            label = f' aria-label="{escape(project["name"], quote=True)}"' if project.get('name_lines') else ''
            anchor = project.get('paper_anchor')
            href = f'../../{project["paper_page"]}' if project.get('paper_page') else project['url']
            if anchor:
                href = f'../../index_backup.html#{anchor}'
            navigation = f' data-paper-anchor="{anchor}" target="_parent"' if anchor else ''
            # Keep each separator with the preceding project when the list wraps.
            separator = '<span class="project-separator" aria-hidden="true">·</span>' if project_index < len(group['projects']) - 1 else ''
            projects.append(f'<span class="project-entry"><a class="project" href="{escape(href, quote=True)}"{navigation}{title}{label}><span>{project_name(project)}</span>{logo}</a>{separator}</span>')
        groups.append(f'''<li class="research-group">
          <div class="research-row">
            <h2 id="group-{i}">{escape(group['name'])}:</h2>
            <div class="projects">{''.join(projects)}</div>
          </div>
        </li>''')
    template = (ROOT / 'site' / 'index.template.html').read_text(encoding='utf-8')
    values = {
        'NAME': escape(profile['name']),
        'META_DESCRIPTION': escape(profile['name'] + ' · ' + profile['tagline'], quote=True),
        'STYLE_VERSION': hashlib.sha256((ROOT / 'site' / 'style.css').read_bytes()).hexdigest()[:12],
        'SCRIPT_VERSION': hashlib.sha256((ROOT / 'site' / 'main.js').read_bytes()).hexdigest()[:12],
        'ANIMATION_SPEED': '9',
        'HOVER_ANIMATION_SPEED': '3',
        'INTRO': animated_intro(profile),
        'AFFILIATIONS': '<span class="affiliation-separator" aria-hidden="true">/</span>'.join(affiliation_markup(item) for item in profile['affiliations']),
        'GROUPS': '\n'.join(groups),
    }
    # One substitution pass prevents user text containing {{...}} from becoming
    # another template instruction.
    return re.sub(r'\{\{([A-Z_]+)\}\}', lambda match: values[match[1]], template)


def build_site(profile, destination):
    site = destination / 'site'
    site.mkdir(parents=True, exist_ok=True)
    # Independent asset copies keep site-only rebuilds from changing README logos.
    assets = build_assets(profile, site)
    (site / 'index.html').write_text(page(profile), encoding='utf-8')
    for source, target in (
        (ROOT / 'site/style.css', site / 'style.css'),
        (ROOT / 'site/main.js', site / 'main.js'),
        (ROOT / 'assets/favicon.svg', site / 'assets/favicon.svg'),
    ):
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.resolve() != target.resolve():
            shutil.copyfile(source, target)
    # Keep existing local/bookmarked entry points working after moving the page.
    (destination / 'index.html').write_text(f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="refresh" content="0; url=site/">
  <title>{escape(profile['name'])}</title>
</head>
<body><a href="site/">Open the profile page</a></body>
</html>
''', encoding='utf-8')
    return {f'site/{name}': svg for name, svg in assets.items()}


def build(profile, destination=ROOT, site_only=False):
    assets = build_site(profile, destination)
    if not site_only:
        assets.update(build_assets(profile, destination))
        markdown = readme(profile)
        (destination / 'README.md').write_text(markdown, encoding='utf-8')
        preview = (ROOT / 'site' / 'readme-preview.template.html').read_text(encoding='utf-8')
        (destination / 'readme-preview.html').write_text(preview.replace('{{README}}', markdown), encoding='utf-8')
    return assets


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', type=Path, default=ROOT / 'profile.json', help='Profile JSON; image paths remain relative to the repository root')
    parser.add_argument('--check', action='store_true', help='Validate configuration and image paths without writing files')
    parser.add_argument('--site-only', action='store_true', help='Build only the dynamic site; leave README, its logos, and its preview untouched')
    args = parser.parse_args()
    try:
        profile = load_profile(args.config, ROOT)
        if args.check:
            print('Profile configuration and image paths are valid.')
        else:
            assets = build(profile, site_only=args.site_only)
            outputs = 'site/index.html and its entry point' if args.site_only else 'README.md, readme-preview.html, site/index.html, and its entry point'
            print(f'Built {outputs}, and {len(assets)} SVG assets from {args.config.name}.')
    except (ValueError, OSError) as error:
        parser.exit(1, f'Profile error: {error}\n')


if __name__ == '__main__':
    main()
